# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateEloWithStartingValues <- function(winner_names, loser_names, winner_match, loser_match, slam_factor, known_elo_names, known_elo_values) {
    .Call('_tennisratingscpp_CalculateEloWithStartingValues', PACKAGE = 'tennisratingscpp', winner_names, loser_names, winner_match, loser_match, slam_factor, known_elo_names, known_elo_values)
}

CalculateElo <- function(winner_names, loser_names, winner_match, loser_match, slam_factor) {
    .Call('_tennisratingscpp_CalculateElo', PACKAGE = 'tennisratingscpp', winner_names, loser_names, winner_match, loser_match, slam_factor)
}

ServeReturnEloStaticK <- function(server_names, returner_names, server_won, k, return_starting_elo = 1410.) {
    .Call('_tennisratingscpp_ServeReturnEloStaticK', PACKAGE = 'tennisratingscpp', server_names, returner_names, server_won, k, return_starting_elo)
}

ServeReturnGlicko <- function(server, returner, server_won, match_number, match_to_match_variance, initial_variance, initial_return_rating = 1410., backward_pass = FALSE) {
    .Call('_tennisratingscpp_ServeReturnGlicko', PACKAGE = 'tennisratingscpp', server, returner, server_won, match_number, match_to_match_variance, initial_variance, initial_return_rating, backward_pass)
}

CalculateGlickoWinExpectation <- function(mu, sigma_sq, mu_j, sigma_sq_j) {
    .Call('_tennisratingscpp_CalculateGlickoWinExpectation', PACKAGE = 'tennisratingscpp', mu, sigma_sq, mu_j, sigma_sq_j)
}

