# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ServeReturnEloStaticK <- function(server_names, returner_names, server_won, k, return_starting_elo = 1410.) {
    .Call('_tennisratingscpp_ServeReturnEloStaticK', PACKAGE = 'tennisratingscpp', server_names, returner_names, server_won, k, return_starting_elo)
}

